### ISSUE TITLE
Not loading.

### ISSUE THREAD

**Issue by ghost** [Spirtix/sodoff#7]
Noob here, mostly fresh PC. Windows 11.

Installed Visual Studio and mitmproxy.

Running `mitmproxy -s mitm-redirect.py` opens up `flows` and blank nothingness.

Running `dotnet run --project src/sodoff.csproj` works as follows:
```
(bunch of warnings)
...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\Untabem\Desktop\sodoff\src\
```

I don't have the original installer so I am using the Windows Store app. This might be the issue.

Just bounces back and forth not loading after about 10 minutes of waiting.

**Comment by Spirtix** [comment]
The game pulls quite a lot of assets from a content server. You would have to host a content server alongside the API and modify the game to connect to your content server and API.

We currently host a private server for a limited amount of test users. I hope we'll be able to let more users in soon.

**Comment by ghost** [comment]
Thanks for the explanation. Will wait.
