### ISSUE TITLE
Game is not loading. 

### ISSUE THREAD

**Issue by jjb-pro** [Spirtix/sodoff#9]
Hello!
First, I would like to thank you for the offline version of the game. Unfortunately, the game does not load on my computer. I have configured the proxy to localhost and port 5000. I first start mitmproxy with the script (I tried both: the script from Spirtix and J-128) via PowerShell. Additionally, I set _ssl_insecure_ in mitmproxy's options to true. After that, I run the project through another PowerShell window. School of Dragons opens and after some time I have this log file: 
`Mono path[0] = 'C:/Program Files (x86)/School of Dragons/DOMain_Data/Managed'
Mono config path = 'C:/Program Files (x86)/School of Dragons/MonoBleedingEdge/etc'
Initialize engine version: 2021.3.16f1 (4016570cf34f)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/School of Dragons/DOMain_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=0
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Intel(R) UHD Graphics 600 (ID=0x3185)
    Vendor:   Intel
    VRAM:     1957 MB
    Driver:   27.20.100.8783
Begin MonoManager ReloadAssembly
- Completed reload, in  0.370 seconds
<RI> Initializing input.
XInput1_3.dll not found. Trying XInput9_1_0.dll instead...
<RI> Input initialized.
<RI> Initialized touch support.
UnloadTime: 0.787400 ms
Curl error 56: Received HTTP code 404 from proxy after CONNECT
Curl error 56: Received HTTP code 404 from proxy after CONNECT
NullReferenceException: Object reference not set to an instance of an object
  at RsResourceManager.Load (System.String inURL, RsResourceEventHandler inCallback, RsResourceType inType, System.Boolean inDontDestroy, System.Boolean inDisableCache, System.Boolean inDownloadOnly, System.Boolean inIgnoreAssetVersion, System.Object inUserData, System.Boolean ignoreReferenceCount) [0x00077] in <9e11d731dd6549988c10af82ae62155c>:0 
  at RsAssetLoader.Load (System.String[] inAssetList, System.String inDataLocation, RsAssetLoader+LoadEventHandler inCallback, System.Boolean inDontDestroy, System.Boolean inIgnoreAssetVersion, System.Object userData) [0x0009c] in <9e11d731dd6549988c10af82ae62155c>:0 
  at RsResourceManager.LoadManifests (ManifestLoadCallback manifestLoadCallback) [0x000a8] in <9e11d731dd6549988c10af82ae62155c>:0 
  at RsResourceManager+BundleResource.Load () [0x00008] in <9e11d731dd6549988c10af82ae62155c>:0 
  at RsResourceManager.LoadAssetFromBundle (System.String inBundleURL, System.String inAssetName, RsResourceEventHandler inCallback, System.Type inType, System.Boolean inDontDestroy, System.Object inUserData) [0x0014e] in <9e11d731dd6549988c10af82ae62155c>:0 
  at FontManager.PreloadAllFonts (System.Boolean replaceFont) [0x000c9] in <9e11d731dd6549988c10af82ae62155c>:0 
  at ProductStartup.Update () [0x000a8] in <9e11d731dd6549988c10af82ae62155c>:0 

Curl error 56: Received HTTP code 404 from proxy after CONNECT
Curl error 56: Received HTTP code 404 from proxy after CONNECT
Curl error 56: Received HTTP code 404 from proxy after CONNECT
Curl error 56: Received HTTP code 404 from proxy after CONNECT
Curl error 56: Received HTTP code 404 from proxy after CONNECT
Curl error 56: Received HTTP code 404 from proxy after CONNECT
Setting up 1 worker threads for Enlighten.
Memory Statistics:
[ALLOC_TEMP_TLS] TLS Allocator
  StackAllocators : 
    [ALLOC_TEMP_MAIN]
      Peak usage frame count: [2.0 KB-4.0 KB]: 8086 frames, [8.0 KB-16.0 KB]: 6708 frames, [4.0 MB-8.0 MB]: 1 frames
      Initial Block Size 4.0 MB
      Current Block Size 7.7 MB
      Peak Allocated Bytes 7.7 MB
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 2]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 110 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 7]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 110 B
      Overflow Count 0
    [ALLOC_TEMP_Loading.PreloadManager]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 33.7 KB
      Overflow Count 4
    [ALLOC_TEMP_UnityGfxDeviceWorker]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 2.5 KB
      Overflow Count 0
    [ALLOC_TEMP_AssetGarbageCollectorHelper]
      Initial Block Size 64.0 KB
      Current Block Size 64.0 KB
      Peak Allocated Bytes 0 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 5]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 110 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 8]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 110 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 9]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 110 B
      Overflow Count 0
    [ALLOC_TEMP_Job.Worker 0]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 212 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 10]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 111 B
      Overflow Count 0
    [ALLOC_TEMP_Loading.AsyncRead]
      Initial Block Size 64.0 KB
      Current Block Size 64.0 KB
      Peak Allocated Bytes 252 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 13]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 111 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 14]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 111 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 6]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 110 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 11]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 111 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 3]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 110 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 0]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 192 B
      Overflow Count 0
    [ALLOC_TEMP_CloudJob.Worker 0]
      Initial Block Size 32.0 KB
      Current Block Size 40.0 KB
      Peak Allocated Bytes 18.7 KB
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 12]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 111 B
      Overflow Count 0
    [ALLOC_TEMP_EnlightenWorker]
      Initial Block Size 64.0 KB
      Current Block Size 64.0 KB
      Peak Allocated Bytes 42 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 15]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 111 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 4]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 110 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 1]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 110 B
      Overflow Count 0
    [ALLOC_TEMP_BatchDeleteObjects]
      Initial Block Size 64.0 KB
      Current Block Size 64.0 KB
      Peak Allocated Bytes 42 B
      Overflow Count 0
[ALLOC_DEFAULT] Dual Thread Allocator
  Peak main deferred allocation count 28
    [ALLOC_BUCKET]
      Large Block size 4.0 MB
      Used Block count 1
      Peak Allocated bytes 1.3 MB
    [ALLOC_DEFAULT_MAIN]
      Peak usage frame count: [8.0 MB-16.0 MB]: 14795 frames
      Requested Block Size 16.0 MB
      Peak Block count 1
      Peak Allocated memory 12.2 MB
      Peak Large allocation bytes 0 B
    [ALLOC_DEFAULT_THREAD]
      Peak usage frame count: [4.0 MB-8.0 MB]: 14795 frames
      Requested Block Size 16.0 MB
      Peak Block count 1
      Peak Allocated memory 6.4 MB
      Peak Large allocation bytes 0 B
[ALLOC_TEMP_JOB_1_FRAME]
  Initial Block Size 2.0 MB
  Used Block Count 1
  Overflow Count (too large) 0
  Overflow Count (full) 0
[ALLOC_TEMP_JOB_2_FRAMES]
  Initial Block Size 2.0 MB
  Used Block Count 1
  Overflow Count (too large) 0
  Overflow Count (full) 0
[ALLOC_TEMP_JOB_4_FRAMES (JobTemp)]
  Initial Block Size 2.0 MB
  Used Block Count 2
  Overflow Count (too large) 0
  Overflow Count (full) 0
[ALLOC_TEMP_JOB_ASYNC (Background)]
  Initial Block Size 1.0 MB
  Used Block Count 3
  Overflow Count (too large) 0
  Overflow Count (full) 0
[ALLOC_GFX] Dual Thread Allocator
  Peak main deferred allocation count 4
    [ALLOC_BUCKET]
      Large Block size 4.0 MB
      Used Block count 1
      Peak Allocated bytes 1.3 MB
    [ALLOC_GFX_MAIN]
      Peak usage frame count: [32.0 KB-64.0 KB]: 14794 frames, [256.0 KB-0.5 MB]: 1 frames
      Requested Block Size 16.0 MB
      Peak Block count 1
      Peak Allocated memory 302.7 KB
      Peak Large allocation bytes 0 B
    [ALLOC_GFX_THREAD]
      Peak usage frame count: [16.0 KB-32.0 KB]: 14795 frames
      Requested Block Size 16.0 MB
      Peak Block count 1
      Peak Allocated memory 19.9 KB
      Peak Large allocation bytes 0 B
[ALLOC_CACHEOBJECTS] Dual Thread Allocator
  Peak main deferred allocation count 1
    [ALLOC_BUCKET]
      Large Block size 4.0 MB
      Used Block count 1
      Peak Allocated bytes 1.3 MB
    [ALLOC_CACHEOBJECTS_MAIN]
      Peak usage frame count: [1.0 MB-2.0 MB]: 14794 frames, [2.0 MB-4.0 MB]: 1 frames
      Requested Block Size 4.0 MB
      Peak Block count 1
      Peak Allocated memory 2.3 MB
      Peak Large allocation bytes 0 B
    [ALLOC_CACHEOBJECTS_THREAD]
      Peak usage frame count: [1.0 MB-2.0 MB]: 14795 frames
      Requested Block Size 4.0 MB
      Peak Block count 1
      Peak Allocated memory 1.5 MB
      Peak Large allocation bytes 0 B
[ALLOC_TYPETREE] Dual Thread Allocator
  Peak main deferred allocation count 0
    [ALLOC_BUCKET]
      Large Block size 4.0 MB
      Used Block count 1
      Peak Allocated bytes 1.3 MB
    [ALLOC_TYPETREE_MAIN]
      Peak usage frame count: [4.0 KB-8.0 KB]: 9 frames, [8.0 KB-16.0 KB]: 14786 frames
      Requested Block Size 2.0 MB
      Peak Block count 1
      Peak Allocated memory 14.6 KB
      Peak Large allocation bytes 0 B
    [ALLOC_TYPETREE_THREAD]
      Peak usage frame count: [16.0 KB-32.0 KB]: 14795 frames
      Requested Block Size 2.0 MB
      Peak Block count 1
      Peak Allocated memory 25.5 KB
      Peak Large allocation bytes 0 B
`

Should the errors occur and will the game also load eventually or does it make no sense to wait?

**Comment by Spirtix** [comment]
The game pulls a lot of assets from a content server. The official assets servers are gone, so ideally you'd have to host your own asset server and redirect the game there. We currently host a private server for a limited amount of test users.

That being said, J-128's script should work because it redirects content requests to a mirror content server. Did you configure the proxy address correctly? The default is localhost:8080. Did you install the mitmproxy certificate?

**Comment by jjb-pro** [comment]
Thanks for the answer. 
I do not have a certificate installed. In my browser, antivirus and Windows I set the port to 5000 because the script forwards the request there or not? Is it enough if I follow this guide ([mitmproxy Docs](https://docs.mitmproxy.org/stable/concepts-certificates/)) or do I need to change something else to host my own content server? I am familiar with many around the .NET Framework, but I have never dealt with the topic "proxy". 

It would be good to automate the configuration and activities that need to be done in the future with for example a simple PowerShell script to give players without any idea about computers a way to play. 

Thanks again for the help and the great project!

**Comment by Spirtix** [comment]
You need to set windows proxy to localhost:8080 (assuming mitmproxy is listening on this port). Then visit [mitm.it](http://mitm.it/), where you should see instructions on how to install the certificate. Use J-128's script in mitmproxy.

This procedure for running the emulator is for development purposes only. We run a server for a limited number of testers, and all they have to do is download a modified game client.

**Comment by jjb-pro** [comment]
Thanks for the help! It was the certificate that I forgot. The game works wonderfully. I created a tutorial that you are welcome to attach to the project. You can find the *.md file as an attachment: [instructions.md](https://github.com/Spirtix/sodoff/files/11999898/instructions.md). 

---

# Temporary setup with redirection of official server requests (on Windows)
Currently, a private server is hosted for a limited amount of test users. This will hopefully change in the future. This guide is for all who want to play immediately and not wait for the improved server. 
## Install .NET
>ℹ️ *.NET is a software framework developed by Microsoft that allows developers to build and run applications on various platforms. It provides a set of tools, libraries that simplifies the development process.* 

Download the official 6th version of .NET from Microsoft: [Download .NET 6.0](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)
Under **Build apps - SDK**, in the table select the link in the cell **Installer, Windows** and the appropriate version for the computer, most likely **x64**. 

After downloading, run the installer and follow the instructions. After the installation, you can delete the downloaded file. 
## Install mitmproxy
>ℹ️ *mitmproxy is a powerful tool that allows you to intercept and inspect network traffic between devices, acting as a "man-in-the-middle" to see and modify the data being exchanged. It helps you to  manipulate that communication for various purposes.*

Download mitmproxy: [mitmproxy - Download](https://downloads.mitmproxy.org/9.0.1/mitmproxy-9.0.1-windows-x64-installer.exe)

Now run the mitmproxy installer and follow the instructions there. 
## Configuration of the proxy
After installation, search for **proxy settings** in Windows settings. Under **manual setup**, select edit. Under **Proxy IP address**, type **http://localhost** and under port, type **8080**. Save this setting now. 

Run PowerShell. You should run it through the Windows Terminal, which is available for download from the Microsoft Store or GitHub. To open PowerShell via the Windows Terminal, simply launch the terminal and select the PowerShell option from the list of available shells. 
>ℹ️ *PowerShell is a command-line shell and scripting language developed by Microsoft. It provides a powerful and flexible environment for managing and automating various tasks on Windows systems. PowerShell is included by default in modern versions of Windows.*

Type the following command to start mitmproxy: `mitmproxy`. Now that mitmproxy started, go into the options and set **ssl_insecure** to **true**. Save these settings. 
>ℹ️*The explanation of how exactly to use mitmproxy is beyond the scope of this manual. For more information, see the official mitmproxy documentation: [mitmproxy - Docs](https://docs.mitmproxy.org/stable/).*

After that, open a browser of your choice. If necessary, search for the proxy settings and configure them to use the system settings. 

Open the page [http://mitm.it/](http://mitm.it/). There you will first find a button to download a Windows certificate. Download it, open it and follow the instructions. If everything worked, you should now see different flows in mitmproxy. Close it now. 
## Downloading the project
Download the **sodoff** project. Unzip the .zip file to a folder of your choice. Also download this python script: [Redirect official server requests - J-128](https://github.com/Spirtix/sodoff/blob/2a8cf3acc46ff1c091b84e13fed383e27fbabc1f/mitm-redirect.py). Replace it with the Python script already included in the project. 
## Starting mitmproxy
Open a new PowerShell window in the project folder: Open the folder in File Explorer where you want to open the PowerShell window. In the address bar of the File Explorer window, type **powershell** and press Enter. Execute the following code to start mitmproxy with the python script: ```mitmproxy -s mitm-redirect.py```. 
## Starting the server
To compile and run the **sodoff** project, run the code in another PowerShell window: `dotnet run --project src/sodoff.csproj`. After you receive information that the server is started, you can start the game. 
## Debugging the game
If you encounter any problems/errors, you can find the School of Dragons log file at: **%appdata%\\..\LocalLow\JumpStart\SoD\Player.log**.
